branches:
  except:
    - /travis/
skip_tags: true

#cache:
#  - C:\strawberry

# XXX known to not work with native Windows perls
# --- at least the dependency Slay::Maker does not work
environment:
  matrix:
#    - perl: activeperl
#      make: dmake
    - perl: cygwinperl
      make: make
#    - perl: strawberryperl
#      make: gmake

install:
  - if %perl%==strawberryperl ( if not exist "C:\strawberry" cinst strawberryperl )
  - if %perl%==strawberryperl   set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - if not %perl%==cygwinperl   perl -v
  - if     %perl%==cygwinperl   c:\cygwin\bin\sh -c "/usr/bin/perl -v"
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - if %perl%==activeperl       ppm install dmake App-cpanminus
  - if not %perl%==cygwinperl   cpanm --installdeps .
  # Install the missing crypt.h for compiling XS modules
  - if     %perl%==cygwinperl   c:\cygwin\setup-x86.exe -q --packages=libcrypt-devel,perl
  - if     %perl%==cygwinperl   c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; (cd /tmp && git clone https://github.com/eserte/travis-helper-cpan-pm.git && ./travis-helper-cpan-pm/travis-helper-cpan-pm --no-sudo)"
  # Fails test suite, so install with -T
  # See also http://www.cpantesters.org/cpan/report/05b8e62e-a914-1014-a63b-77b394f39f87
  - if     %perl%==cygwinperl   c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; cpan -T Test::File"

build_script:
  - if     %perl%==cygwinperl   c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; cpan -t ."
  - if not %perl%==cygwinperl ( perl Makefile.PL && %make% test )
